Repository TravelRole/roleTravel-backend, pull requests merged in 2023-04, with the labels that each got.

#27 Feat #26 properties encrypt
  .gitignore
  build.gradle
  src/main/java/com/travel/role/global/config/encrypt/JasyptConfig.java
  src/main/resources/application-mail.yml
  src/main/resources/application-oauth.yml
Labels: enhancement

#29 Feat #28 make room api
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/dao/ParticipantRoleRepository.java
  src/main/java/com/travel/role/domain/room/dao/RoomParticipantRepository.java
  src/main/java/com/travel/role/domain/room/dao/RoomRepository.java
  src/main/java/com/travel/role/domain/room/domain/Room.java
  src/main/java/com/travel/role/domain/room/dto/MakeRoomRequestDTO.java
  src/main/java/com/travel/role/domain/room/exception/InvalidLocalDateException.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/domain/user/domain/User.java
  src/main/java/com/travel/role/global/auth/service/AuthService.java
  src/main/java/com/travel/role/global/auth/service/CustomOAuth2UserService.java
  src/main/java/com/travel/role/global/exception/ExceptionMessage.java
  src/main/java/com/travel/role/global/exception/GlobalExceptionHandler.java
  src/main/java/com/travel/role/global/util/PasswordGenerator.java
  src/test/java/com/travel/role/domain/room/service/RoomServiceTest.java
Labels: 👀Feature

#31 Feat #30개인준비물을위한entity구성
  src/main/java/com/travel/role/domain/room/domain/TravelEssentials.java
  src/main/java/com/travel/role/domain/user/domain/User.java
Labels: 👀Feature

#37 fix: RequestDTO 직렬화수정
  src/main/java/com/travel/role/domain/user/dto/ConfirmUserRequestDTO.java
  src/main/java/com/travel/role/domain/user/dto/NewPasswordRequestDTO.java
Labels: 🐞BugFix

#44 Feat #35 회원 프로필 조회 기능 작성
  src/main/java/com/travel/role/domain/user/controller/UserController.java
  src/main/java/com/travel/role/domain/user/dto/UserProfileDetailResDTO.java
  src/main/java/com/travel/role/domain/user/service/UserService.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
  src/test/java/com/travel/role/domain/user/service/UserServiceTest.java
Labels: 👀Feature

#46 feat: deploy를 위해, redirect path
  src/main/resources/application-oauth.yml
Labels: 🛠️Fix

#47 Feat #45 회원 프로필 수정 기능 작성
  src/main/java/com/travel/role/domain/user/controller/UserController.java
  src/main/java/com/travel/role/domain/user/domain/User.java
  src/main/java/com/travel/role/domain/user/dto/UserProfileModifyReqDTO.java
  src/main/java/com/travel/role/domain/user/dto/auth/SignUpRequestDTO.java
  src/main/java/com/travel/role/domain/user/service/UserService.java
  src/main/java/com/travel/role/global/exception/ExceptionMessage.java
  src/main/java/com/travel/role/global/util/FormatterUtil.java
  src/test/java/com/travel/role/domain/user/service/UserServiceTest.java
Labels: 👀Feature

#48 user profile 조회시 응답 필드 추가
  src/main/java/com/travel/role/domain/user/dto/UserProfileDetailResDTO.java
  src/test/java/com/travel/role/domain/user/service/UserServiceTest.java
Labels: 🛠️Fix

#50 Feat #34 get room list
  build.gradle
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/dao/RoomQuerydsl.java
  src/main/java/com/travel/role/domain/room/dao/RoomQuerydslImpl.java
  src/main/java/com/travel/role/domain/room/dao/RoomRepository.java
  src/main/java/com/travel/role/domain/room/domain/Room.java
  src/main/java/com/travel/role/domain/room/domain/RoomParticipant.java
  src/main/java/com/travel/role/domain/room/dto/MakeRoomRequestDTO.java
  src/main/java/com/travel/role/domain/room/dto/MemberDTO.java
  src/main/java/com/travel/role/domain/room/dto/RoomResponseDTO.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/domain/user/domain/User.java
  src/main/java/com/travel/role/domain/user/dto/auth/SignUpRequestDTO.java
  src/main/java/com/travel/role/global/auth/dto/AuthResponse.java
  src/main/java/com/travel/role/global/auth/dto/SignInRequestDTO.java
  src/main/java/com/travel/role/global/auth/dto/SignUpRequestDTO.java
  src/main/java/com/travel/role/global/config/querydsl/QuerydslConfig.java
  src/main/resources/application.yml
  src/test/java/com/travel/role/domain/room/RoomTest.java
  src/test/java/com/travel/role/domain/room/service/RoomServiceTest.java
Labels: 👀Feature

#51 Feat #49 회원 비밀번호 수정 기능 작성
  src/main/java/com/travel/role/domain/user/controller/UserController.java
  src/main/java/com/travel/role/domain/user/dto/UserPasswordModifyReqDTO.java
  src/main/java/com/travel/role/domain/user/dto/auth/SignUpRequestDTO.java
  src/main/java/com/travel/role/domain/user/exception/InputValueNotMatchException.java
  src/main/java/com/travel/role/domain/user/service/UserService.java
  src/main/java/com/travel/role/global/exception/ExceptionMessage.java
  src/main/java/com/travel/role/global/exception/GlobalExceptionHandler.java
  src/test/java/com/travel/role/domain/user/service/UserServiceTest.java
Labels: 👀Feature

#53 Feat #38가고싶은장소를위한entity구성
  src/main/java/com/travel/role/domain/room/controller/WantPlaceController.java
  src/main/java/com/travel/role/domain/room/dao/RoomRepository.java
  src/main/java/com/travel/role/domain/room/dao/WantPlaceRepository.java
  src/main/java/com/travel/role/domain/room/domain/Room.java
  src/main/java/com/travel/role/domain/room/domain/RoomParticipant.java
  src/main/java/com/travel/role/domain/room/domain/WantPlace.java
  src/main/java/com/travel/role/domain/room/dto/WantPlaceRequestDTO.java
  src/main/java/com/travel/role/domain/room/service/WantPlaceService.java
  src/main/java/com/travel/role/domain/user/dto/auth/SignUpRequestDTO.java
  src/main/java/com/travel/role/domain/user/exception/RoomInfoNotFoundException.java
  src/main/java/com/travel/role/domain/user/exception/UserNotParticipateRoomException.java
  src/main/java/com/travel/role/global/auth/service/mail/MailService.java
  src/main/java/com/travel/role/global/exception/ExceptionMessage.java
  src/main/java/com/travel/role/global/exception/GlobalExceptionHandler.java
  src/test/java/com/travel/role/domain/room/service/WantPlaceServiceTest.java
  src/test/java/com/travel/role/global/auth/service/AuthServiceTest.java
Labels: 👀Feature

#55 Feat #52 회원 프로필 사진 변경 기능 작성
  build.gradle
  src/main/java/com/travel/role/domain/user/controller/UserController.java
  src/main/java/com/travel/role/domain/user/domain/User.java
  src/main/java/com/travel/role/domain/user/service/UserService.java
  src/main/java/com/travel/role/global/config/aws/AWSS3Config.java
  src/main/java/com/travel/role/global/exception/ExceptionMessage.java
  src/main/java/com/travel/role/global/exception/GlobalExceptionHandler.java
  src/main/java/com/travel/role/global/exception/S3ImageNotFoundException.java
  src/main/java/com/travel/role/global/s3/S3Service.java
  src/main/resources/application-cloud.yml
  src/main/resources/application.yml
Labels: 👀Feature

#61 Feat #60 add room list column
  src/main/java/com/travel/role/domain/room/dto/RoomResponseDTO.java
  src/main/resources/application-oauth.yml
Labels: 👀Feature

#58 feat: 가고싶은 장소 조회 api
  src/main/java/com/travel/role/domain/room/controller/WantPlaceController.java
  src/main/java/com/travel/role/domain/room/dao/WantPlaceRepository.java
  src/main/java/com/travel/role/domain/room/domain/RoomParticipant.java
  src/main/java/com/travel/role/domain/room/domain/WantPlace.java
  src/main/java/com/travel/role/domain/room/dto/WantPlaceDTO.java
  src/main/java/com/travel/role/domain/room/dto/WantPlaceResponseDTO.java
  src/main/java/com/travel/role/domain/room/service/WantPlaceService.java
  src/test/java/com/travel/role/domain/room/RoomTest.java
  src/test/java/com/travel/role/domain/room/service/WantPlaceServiceTest.java
Labels: 👀Feature

#65 H2 -> MySQL 로 DB 변경
  build.gradle
  src/main/java/com/travel/role/global/auth/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🛠️Fix

#63 Feat #59가고싶은장소삭제api
  src/main/java/com/travel/role/domain/room/controller/WantPlaceController.java
  src/main/java/com/travel/role/domain/room/dao/ParticipantRoleRepository.java
  src/main/java/com/travel/role/domain/room/dao/RoomParticipantRepository.java
  src/main/java/com/travel/role/domain/room/dao/WantPlaceRepository.java
  src/main/java/com/travel/role/domain/room/domain/ParticipantRole.java
  src/main/java/com/travel/role/domain/room/service/WantPlaceService.java
  src/main/java/com/travel/role/domain/user/exception/PlaceInfoNotFoundException.java
  src/main/java/com/travel/role/domain/user/exception/UserNotParticipateRoomException.java
  src/main/java/com/travel/role/global/exception/ExceptionMessage.java
  src/main/java/com/travel/role/global/exception/GlobalExceptionHandler.java
Labels: 👀Feature

#66 Feat #56 댓글 CRUD 구현
  build.gradle
  src/main/java/com/travel/role/domain/comment/controller/CommentController.java
  src/main/java/com/travel/role/domain/comment/dao/CommentRepository.java
  src/main/java/com/travel/role/domain/comment/dto/CommentListResDTO.java
  src/main/java/com/travel/role/domain/comment/dto/CommentReqDTO.java
  src/main/java/com/travel/role/domain/comment/dto/CommentResDTO.java
  src/main/java/com/travel/role/domain/comment/entity/Comment.java
  src/main/java/com/travel/role/domain/comment/exception/CommentInfoNotFoundException.java
  src/main/java/com/travel/role/domain/comment/service/CommentService.java
  src/main/java/com/travel/role/domain/room/dao/RoomParticipantRepository.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/domain/room/service/WantPlaceService.java
  src/main/java/com/travel/role/domain/user/exception/AlreadyExistUserException.java
  src/main/java/com/travel/role/domain/user/exception/RoomInfoNotFoundException.java
  src/main/java/com/travel/role/domain/user/exception/UserInfoNotFoundException.java
  src/main/java/com/travel/role/domain/user/service/UserService.java
  src/main/java/com/travel/role/global/auth/exception/NotExistTokenException.java
  src/main/java/com/travel/role/global/auth/service/AuthService.java
  src/main/java/com/travel/role/global/auth/service/CustomOAuth2UserService.java
  src/main/java/com/travel/role/global/exception/ExceptionMessage.java
  src/main/java/com/travel/role/global/exception/GlobalExceptionHandler.java
  src/main/java/com/travel/role/global/exception/ResourceOperationAccessDeniedException.java
  src/test/java/com/travel/role/config/TestConfig.java
  src/test/java/com/travel/role/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/travel/role/domain/comment/service/CommentServiceTest.java
  src/test/resources/application.yml
Labels: 👀Feature

#69 Fix #68 erd수정에따른코드수정
  src/main/java/com/travel/role/domain/room/dao/ParticipantRoleRepository.java
  src/main/java/com/travel/role/domain/room/dao/RoomRepository.java
  src/main/java/com/travel/role/domain/room/domain/ParticipantRole.java
  src/main/java/com/travel/role/domain/room/domain/RoomParticipant.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/domain/room/service/WantPlaceService.java
  src/test/java/com/travel/role/domain/room/RoomTest.java
  src/test/java/com/travel/role/domain/room/service/WantPlaceServiceTest.java
Labels: 🛠️Fix

#64 Feat #62 room invite code
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/dao/RoomQuerydsl.java
  src/main/java/com/travel/role/domain/room/dao/RoomRepository.java
  src/main/java/com/travel/role/domain/room/domain/Room.java
  src/main/java/com/travel/role/domain/room/dto/WantPlaceResponseDTO.java
  src/main/java/com/travel/role/domain/room/exception/UserHaveNotPrivilegeException.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/global/auth/service/AuthService.java
  src/main/java/com/travel/role/global/exception/ExceptionMessage.java
  src/main/java/com/travel/role/global/exception/GlobalExceptionHandler.java
  src/main/java/com/travel/role/global/util/PasswordGenerator.java
  src/test/java/com/travel/role/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/travel/role/domain/room/RoomTest.java
  src/test/java/com/travel/role/domain/room/service/RoomServiceTest.java
  src/test/java/com/travel/role/domain/room/service/WantPlaceServiceTest.java
Labels: 👀Feature

#73 Feat #72 room image
  src/main/java/com/travel/role/domain/room/domain/Room.java
  src/main/java/com/travel/role/domain/room/dto/MakeRoomRequestDTO.java
  src/main/java/com/travel/role/domain/room/dto/RoomResponseDTO.java
  src/test/java/com/travel/role/domain/room/RoomTest.java
  src/test/java/com/travel/role/domain/room/service/RoomServiceTest.java
Labels: 👀Feature

#78 Hotfix: 방정보 가져오는 로직 오류
  src/main/java/com/travel/role/domain/room/dao/RoomQuerydslImpl.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/test/java/com/travel/role/domain/room/RoomTest.java
Labels: 🐞BugFix

#79 Hotfix : 중복회원 제거 안함 수정
  src/main/java/com/travel/role/domain/room/service/RoomService.java
Labels: 🐞BugFix

#75 Feat: 초대 링크로 들어왔을때 로직 구현
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/dao/RoomQuerydsl.java
  src/main/java/com/travel/role/domain/room/dao/RoomQuerydslImpl.java
  src/main/java/com/travel/role/domain/room/dao/RoomRepository.java
  src/main/java/com/travel/role/domain/room/dto/InviteResponseDTO.java
  src/main/java/com/travel/role/domain/room/exception/AlreadyExistInRoomException.java
  src/main/java/com/travel/role/domain/room/exception/InvalidInviteCode.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/global/exception/ExceptionMessage.java
  src/main/java/com/travel/role/global/exception/GlobalExceptionHandler.java
  src/test/java/com/travel/role/domain/room/service/RoomServiceTest.java
Labels: 👀Feature

#80 Feat #67 여행 준비물 api 구현
  src/main/java/com/travel/role/domain/room/controller/TravelEssentialController.java
  src/main/java/com/travel/role/domain/room/dao/TravelEssentialQuerydsl.java
  src/main/java/com/travel/role/domain/room/dao/TravelEssentialQuerydslImpl.java
  src/main/java/com/travel/role/domain/room/dao/TravelEssentialRepository.java
  src/main/java/com/travel/role/domain/room/domain/EssentialCategory.java
  src/main/java/com/travel/role/domain/room/domain/TravelEssentials.java
  src/main/java/com/travel/role/domain/room/dto/TravelEssentialCheckReqDTO.java
  src/main/java/com/travel/role/domain/room/dto/TravelEssentialDeleteReqDTO.java
  src/main/java/com/travel/role/domain/room/dto/TravelEssentialItemDTO.java
  src/main/java/com/travel/role/domain/room/dto/TravelEssentialReqDTO.java
  src/main/java/com/travel/role/domain/room/dto/TravelEssentialResDTO.java
  src/main/java/com/travel/role/domain/room/service/TravelEssentialService.java
  src/main/java/com/travel/role/global/exception/ExceptionMessage.java
Labels: 👀Feature

#84 Refactor #83 준비물 Service 리팩토링
  src/main/java/com/travel/role/domain/travelessential/controller/TravelEssentialController.java
  src/main/java/com/travel/role/domain/travelessential/repository/querydsl/TravelEssentialQuerydslImpl.java
  src/main/java/com/travel/role/domain/travelessential/service/TravelEssentialReadService.java
  src/main/java/com/travel/role/domain/travelessential/service/TravelEssentialService.java
Labels: ♼Refactor

#87 Feat #81 회원 프로필 이미지 삭제 기능 구현
  src/main/java/com/travel/role/domain/user/controller/UserController.java
  src/main/java/com/travel/role/domain/user/service/UserService.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
  src/main/java/com/travel/role/global/s3/ImageProperty.java
  src/main/java/com/travel/role/global/s3/S3Service.java
Labels: 👀Feature

#86 Refactor: UserReadService에서 오버로딩 메서드 변경
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/domain/user/service/UserReadService.java
  src/main/java/com/travel/role/domain/wantplace/controller/WantPlaceController.java
  src/main/java/com/travel/role/domain/wantplace/service/WantPlaceService.java
  src/test/java/com/travel/role/integration/room/RoomTest.java
  src/test/java/com/travel/role/unit/room/service/RoomServiceTest.java
Labels: ♼Refactor
