Repository TravelRole/roleTravel-backend, pull requests merged in 2023-05, with the labels that each got.

#90 Feat #54가고싶은장소일정에추가하는api작성
  src/main/java/com/travel/role/domain/board/controller/BoardController.java
  src/main/java/com/travel/role/domain/board/dto/request/BoardRequestDTO.java
  src/main/java/com/travel/role/domain/board/entity/Board.java
  src/main/java/com/travel/role/domain/board/entity/BookInfo.java
  src/main/java/com/travel/role/domain/board/entity/Category.java
  src/main/java/com/travel/role/domain/board/entity/ScheduleInfo.java
  src/main/java/com/travel/role/domain/board/repository/BoardRepository.java
  src/main/java/com/travel/role/domain/board/repository/BookInfoRepository.java
  src/main/java/com/travel/role/domain/board/repository/ScheduleInfoRepository.java
  src/main/java/com/travel/role/domain/board/service/BoardService.java
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/dto/response/TimeResponseDTO.java
  src/main/java/com/travel/role/domain/room/entity/Room.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/test/java/com/travel/role/unit/room/service/BoardServiceTest.java
  src/test/java/com/travel/role/unit/room/service/RoomServiceTest.java
Labels: 👀Feature

#93 Feat #92예약페이지조회api작성
  src/main/java/com/travel/role/domain/board/controller/BoardController.java
  src/main/java/com/travel/role/domain/board/dto/response/BookInfoResponseDTO.java
  src/main/java/com/travel/role/domain/board/entity/Board.java
  src/main/java/com/travel/role/domain/board/repository/BoardRepository.java
  src/main/java/com/travel/role/domain/board/service/BoardService.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
  src/test/java/com/travel/role/unit/room/service/BoardServiceTest.java
Labels: 👀Feature

#96 Refactor: properties 환경 분리
  src/main/resources/application-common.yml
  src/main/resources/application-db.yml
  src/main/resources/application.yml
Labels: ♼Refactor

#94 Fix #88 댓글 기능 수정
  src/main/java/com/travel/role/domain/comment/controller/CommentController.java
  src/main/java/com/travel/role/domain/comment/dto/response/CommentResDTO.java
  src/main/java/com/travel/role/domain/comment/entity/Comment.java
  src/main/java/com/travel/role/domain/comment/repository/CommentRepository.java
  src/main/java/com/travel/role/domain/comment/repository/querydsl/CommentQuerydsl.java
  src/main/java/com/travel/role/domain/comment/repository/querydsl/CommentQuerydslImpl.java
  src/main/java/com/travel/role/domain/comment/service/CommentReadService.java
  src/main/java/com/travel/role/domain/comment/service/CommentService.java
  src/main/java/com/travel/role/domain/room/entity/RoomRole.java
  src/main/java/com/travel/role/domain/user/dto/SimpleUserInfoResDTO.java
  src/test/java/com/travel/role/unit/comment/service/CommentReadServiceTest.java
  src/test/java/com/travel/role/unit/comment/service/CommentServiceTest.java
  src/test/java/com/travel/role/unit/commnet/repository/CommentRepositoryTest.java
  src/test/java/com/travel/role/unit/commnet/service/CommentServiceTest.java
Labels: 🛠️Fix

#97 Feat #89 kakao 로그인 구현
  src/main/java/com/travel/role/domain/room/repository/RoomParticipantRepository.java
  src/main/java/com/travel/role/domain/room/repository/querydsl/RoomParticipantQuerydsl.java
  src/main/java/com/travel/role/domain/room/repository/querydsl/RoomParticipantQuerydslImpl.java
  src/main/java/com/travel/role/domain/room/repository/querydsl/RoomQuerydsl.java
  src/main/java/com/travel/role/domain/room/repository/querydsl/RoomQuerydslImpl.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/domain/user/controller/UserController.java
  src/main/java/com/travel/role/domain/user/entity/Provider.java
  src/main/java/com/travel/role/domain/user/service/UserReadService.java
  src/main/java/com/travel/role/global/auth/controller/AuthController.java
  src/main/java/com/travel/role/global/auth/dto/TokenResponse.java
  src/main/java/com/travel/role/global/auth/oauth/OAuthAttributes.java
  src/main/java/com/travel/role/global/auth/oauth/filter/CustomOAuth2LogoutHandler.java
  src/main/java/com/travel/role/global/auth/oauth/kakao/KakaoOAuth2UserInfo.java
  src/main/java/com/travel/role/global/auth/service/AuthService.java
  src/main/java/com/travel/role/global/auth/service/CustomOAuth2UserService.java
  src/main/java/com/travel/role/global/auth/service/CustomUserDetailService.java
  src/main/java/com/travel/role/global/auth/service/RefreshTokenCookieProvider.java
  src/main/java/com/travel/role/global/auth/service/TokenProvider.java
  src/main/java/com/travel/role/global/auth/service/handler/OAuth2FailureHandler.java
  src/main/java/com/travel/role/global/auth/service/handler/OAuth2SuccessHandler.java
  src/main/java/com/travel/role/global/auth/token/JwtAuthenticationFilter.java
  src/main/java/com/travel/role/global/config/auth/SecurityConfig.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
  src/main/java/com/travel/role/global/util/Constants.java
  src/main/java/com/travel/role/global/util/PasswordGenerator.java
  src/main/resources/application-oauth.yml
  src/test/java/com/travel/role/unit/auth/service/AuthServiceTest.java
  src/test/java/com/travel/role/unit/room/service/RoomServiceTest.java
Labels: 👀Feature

#106 Fix #105map으로메소드수정
  src/main/java/com/travel/role/domain/wantplace/service/WantPlaceService.java
Labels: 🛠️Fix

#104 Feat #103 댓글 페이징 적용
  src/main/java/com/travel/role/domain/comment/controller/CommentController.java
  src/main/java/com/travel/role/domain/comment/dto/response/CommentListResDTO.java
  src/main/java/com/travel/role/domain/comment/dto/response/PageResDTO.java
  src/main/java/com/travel/role/domain/comment/repository/querydsl/CommentQuerydsl.java
  src/main/java/com/travel/role/domain/comment/repository/querydsl/CommentQuerydslImpl.java
  src/main/java/com/travel/role/domain/comment/service/CommentReadService.java
  src/main/java/com/travel/role/domain/comment/service/CommentService.java
  src/main/java/com/travel/role/global/domain/dto/PageInfo.java
  src/test/java/com/travel/role/unit/comment/service/CommentReadServiceTest.java
Labels: 🛠️Fix

#107 Refactor: auth로 User 분리
  src/main/java/com/travel/role/domain/user/dto/UserProfileDetailResDTO.java
  src/main/java/com/travel/role/domain/user/entity/User.java
  src/main/java/com/travel/role/domain/user/repository/UserRepository.java
  src/main/java/com/travel/role/domain/user/service/UserReadService.java
  src/main/java/com/travel/role/domain/user/service/UserService.java
  src/main/java/com/travel/role/global/auth/controller/AuthController.java
  src/main/java/com/travel/role/global/auth/entity/AuthInfo.java
  src/main/java/com/travel/role/global/auth/oauth/filter/CustomOAuth2LogoutHandler.java
  src/main/java/com/travel/role/global/auth/repository/AuthReadService.java
  src/main/java/com/travel/role/global/auth/repository/AuthRepository.java
  src/main/java/com/travel/role/global/auth/service/AuthService.java
  src/main/java/com/travel/role/global/auth/service/CustomOAuth2UserService.java
  src/main/java/com/travel/role/global/auth/service/CustomUserDetailService.java
  src/main/java/com/travel/role/global/auth/service/handler/OAuth2SuccessHandler.java
  src/main/java/com/travel/role/global/auth/token/UserPrincipal.java
  src/test/java/com/travel/role/unit/auth/service/AuthServiceTest.java
  src/test/java/com/travel/role/unit/room/service/RoomServiceTest.java
  src/test/java/com/travel/role/unit/user/service/UserServiceTest.java
Labels: ♼Refactor

#108 Hotfix : ProviderId 저장이 누락되어있는 오류 발견
  src/main/java/com/travel/role/global/auth/entity/AuthInfo.java
  src/main/java/com/travel/role/global/auth/service/CustomOAuth2UserService.java
Labels: 🐞BugFix

#111 Fix #109예약erd수정
  src/main/java/com/travel/role/domain/board/dto/response/BookInfoResponseDTO.java
  src/main/java/com/travel/role/domain/board/entity/AccountingInfo.java
  src/main/java/com/travel/role/domain/board/entity/Board.java
  src/main/java/com/travel/role/domain/board/entity/BookInfo.java
  src/main/java/com/travel/role/domain/board/repository/AccountingInfoRepository.java
  src/main/java/com/travel/role/domain/board/repository/BoardRepository.java
  src/main/java/com/travel/role/domain/board/service/BoardService.java
  src/test/java/com/travel/role/unit/room/service/BoardServiceTest.java
Labels: 🛠️Fix

#113 Feat #112 여행 경비 수정 기능
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/dto/request/ExpensesRequestDTO.java
  src/main/java/com/travel/role/domain/room/entity/Room.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
  src/main/java/com/travel/role/global/exception/room/ExpenseLessThanZeroException.java
Labels: 👀Feature

#115 Fix #114 댓글 조회 기능 수정
  src/main/java/com/travel/role/domain/comment/controller/CommentController.java
  src/main/java/com/travel/role/domain/comment/dto/response/CommentResDTO.java
  src/main/java/com/travel/role/domain/comment/repository/querydsl/CommentQuerydslImpl.java
Labels: 🛠️Fix

#118 Feat #110 room 수정 API
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/dto/request/RoomModifiedRequestDTO.java
  src/main/java/com/travel/role/domain/room/dto/request/RoomRoleDTO.java
  src/main/java/com/travel/role/domain/room/entity/ParticipantRole.java
  src/main/java/com/travel/role/domain/room/entity/Room.java
  src/main/java/com/travel/role/domain/room/repository/ParticipantRoleRepository.java
  src/main/java/com/travel/role/domain/room/repository/querydsl/ParticipantRoleQuerydsl.java
  src/main/java/com/travel/role/domain/room/repository/querydsl/ParticipantRoleQuerydslImpl.java
  src/main/java/com/travel/role/domain/room/service/ParticipantRoleReadService.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
  src/main/java/com/travel/role/global/exception/room/AdminIsOnlyOneException.java
  src/test/java/com/travel/role/integration/room/RoomTest.java
  src/test/java/com/travel/role/unit/room/service/ParticipantRoleReadServiceTest.java
  src/test/java/com/travel/role/unit/room/service/RoomServiceTest.java
  src/test/resources/application.yml
  src/test/resources/db/test.sql
Labels: 👀Feature

#119 회계 도메인 패키지 구조 변경
  src/main/java/com/travel/role/domain/accounting/controller/AccountingInfoController.java
  src/main/java/com/travel/role/domain/accounting/dto/request/ExpenseDetailCreateReqDTO.java
  src/main/java/com/travel/role/domain/accounting/dto/response/ExpenseDetailCreateResDTO.java
  src/main/java/com/travel/role/domain/accounting/entity/AccountingInfo.java
  src/main/java/com/travel/role/domain/accounting/entity/Category.java
  src/main/java/com/travel/role/domain/accounting/entity/PaymentMethod.java
  src/main/java/com/travel/role/domain/accounting/repository/AccountingInfoRepository.java
  src/main/java/com/travel/role/domain/accounting/service/AccountingInfoService.java
  src/main/java/com/travel/role/domain/board/dto/request/BoardRequestDTO.java
  src/main/java/com/travel/role/domain/board/dto/request/BookRequestDTO.java
  src/main/java/com/travel/role/domain/board/dto/response/BookInfoResponseDTO.java
  src/main/java/com/travel/role/domain/board/entity/Board.java
  src/main/java/com/travel/role/domain/board/entity/Category.java
  src/main/java/com/travel/role/domain/board/entity/PaymentMethod.java
  src/main/java/com/travel/role/domain/board/service/BoardReadService.java
  src/main/java/com/travel/role/domain/board/service/BoardService.java
  src/main/java/com/travel/role/domain/room/entity/RoomRole.java
  src/main/java/com/travel/role/domain/room/service/ParticipantRoleReadService.java
  src/main/java/com/travel/role/global/exception/GlobalExceptionHandler.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
  src/main/java/com/travel/role/global/util/FormatterUtil.java
  src/test/java/com/travel/role/unit/room/service/BoardServiceTest.java
Labels: ♼Refactor

#121 Feat #120 공동 경비 조회 api 작성
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/dto/response/ExpenseResponseDTO.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
Labels: 👀Feature

#123 Fix #122 댓글 조회 페이징 관련 필드 수정
  src/main/java/com/travel/role/global/domain/dto/PageInfo.java
Labels: 🛠️Fix

#125 fix: RDS url 주소 변경
  src/main/resources/application-db.yml
Labels: 🐞BugFix

#127 fix: username과 password를 동일한것으로 복사한 것 수정
  src/main/resources/application-db.yml
Labels: 🐞BugFix

#128 fix: jasypt로 배포하기 위한, 설정파일 추가
  build.gradle
Labels: 🐞BugFix

#126 Fix #124지출내역저장방식수정
  src/main/java/com/travel/role/domain/accounting/entity/AccountingInfo.java
  src/main/java/com/travel/role/domain/board/controller/BoardController.java
  src/main/java/com/travel/role/domain/board/dto/request/BookInfoRequestDTO.java
  src/main/java/com/travel/role/domain/board/dto/request/BookedRequestDTO.java
  src/main/java/com/travel/role/domain/board/entity/BookInfo.java
  src/main/java/com/travel/role/domain/board/service/BoardService.java
  src/main/java/com/travel/role/global/exception/GlobalExceptionHandler.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
Labels: 🛠️Fix

#129 Refactor room 수정 API valid추가
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/dto/request/RoomModifiedRequestDTO.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
Labels: 🛠️Fix

#134 fix: 타입 수정
  src/main/java/com/travel/role/domain/accounting/dto/request/ExpenseDetailCreateReqDTO.java
  src/main/java/com/travel/role/domain/accounting/dto/response/ExpenseDetailCreateResDTO.java
  src/main/java/com/travel/role/domain/accounting/entity/AccountingInfo.java
  src/main/java/com/travel/role/domain/board/dto/request/BookedRequestDTO.java
  src/main/java/com/travel/role/domain/board/service/BoardService.java
Labels: 🛠️Fix

#135 Feat #132 지출 내역 조회 api
  src/main/java/com/travel/role/domain/accounting/controller/AccountingInfoController.java
  src/main/java/com/travel/role/domain/accounting/dto/response/ExpenseDetailResDTO.java
  src/main/java/com/travel/role/domain/accounting/dto/response/ExpenseDetailsResDTO.java
  src/main/java/com/travel/role/domain/accounting/repository/AccountingInfoRepository.java
  src/main/java/com/travel/role/domain/accounting/repository/querydsl/AccountingInfoQuerydsl.java
  src/main/java/com/travel/role/domain/accounting/repository/querydsl/AccountingInfoQuerydslImpl.java
  src/main/java/com/travel/role/domain/accounting/service/AccountingInfoReadService.java
  src/main/java/com/travel/role/global/config/auth/WebMvcConfig.java
  src/main/java/com/travel/role/global/converter/LocalDateRequestConverter.java
  src/main/java/com/travel/role/global/converter/PaymentMethodRequestConverter.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
Labels: 👀Feature

#136 feat: basic profile userId 추가
  src/main/java/com/travel/role/domain/user/dto/UserProfileResponseDTO.java
  src/main/java/com/travel/role/domain/user/service/UserService.java
Labels: 🛠️Fix

#138 Fix #137 예약 정보로부터 연동된 지출 내역인지 확인할 수 있는 필드 추가
  src/main/java/com/travel/role/domain/accounting/dto/response/ExpenseDetailResDTO.java
Labels: 👀Feature

#140 Feat #130 총무 방 수정 정보 불러오는 API 작성
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/dto/response/RoomInfoResponseDTO.java
  src/main/java/com/travel/role/domain/room/dto/response/RoomRoleInfoDTO.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/test/java/com/travel/role/integration/room/RoomTest.java
  src/test/resources/db/test.sql
Labels: 👀Feature

#141 Feat #130 모든 여행 계획 일정 가져오는 로직 작성
  src/main/java/com/travel/role/domain/board/repository/BoardRepository.java
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/dto/response/AllPlanDTO.java
  src/main/java/com/travel/role/domain/room/dto/response/AllPlanResponseDTO.java
  src/main/java/com/travel/role/domain/room/dto/response/ScheduleDTO.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/resources/application-db.yml
  src/test/java/com/travel/role/integration/room/RoomTest.java
  src/test/resources/application.yml
  src/test/resources/db/test.sql
Labels: 👀Feature

#143 Feat #139 지출 내역 수정
  src/main/java/com/travel/role/domain/accounting/controller/AccountingInfoController.java
  src/main/java/com/travel/role/domain/accounting/dto/request/ExpenseDetailModifyReqDTO.java
  src/main/java/com/travel/role/domain/accounting/dto/response/ExpenseDetailModifyResDTO.java
  src/main/java/com/travel/role/domain/accounting/entity/AccountingInfo.java
  src/main/java/com/travel/role/domain/accounting/service/AccountingInfoReadService.java
  src/main/java/com/travel/role/domain/accounting/service/AccountingInfoService.java
Labels: 👀Feature

#147 Fix #146 location 값 추가
  src/main/java/com/travel/role/domain/room/dto/request/RoomModifiedRequestDTO.java
  src/main/java/com/travel/role/domain/room/dto/response/RoomInfoResponseDTO.java
  src/main/java/com/travel/role/domain/room/entity/Room.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/test/java/com/travel/role/integration/room/RoomTest.java
  src/test/java/com/travel/role/unit/room/service/RoomServiceTest.java
Labels: 🛠️Fix

#145 Feat #144 지출 내역 삭제
  src/main/java/com/travel/role/domain/accounting/controller/AccountingInfoController.java
  src/main/java/com/travel/role/domain/accounting/service/AccountingInfoService.java
Labels: 👀Feature

#151 Feat #148 사이드바 API 작성
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/dto/response/SidebarResponseDTO.java
  src/main/java/com/travel/role/domain/room/repository/ParticipantRoleRepository.java
  src/main/java/com/travel/role/domain/room/service/ParticipantRoleReadService.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/test/java/com/travel/role/integration/room/RoomTest.java
Labels: 👀Feature

#158 Fix #157 회계 정보에서 예약과 연동된 항목은 수정, 삭제가 불가능하도록 변경
  src/main/java/com/travel/role/domain/accounting/entity/AccountingInfo.java
  src/main/java/com/travel/role/domain/accounting/service/AccountingInfoReadService.java
  src/main/java/com/travel/role/domain/accounting/service/AccountingInfoService.java
  src/main/java/com/travel/role/domain/board/service/BoardReadService.java
  src/main/java/com/travel/role/global/exception/GlobalExceptionHandler.java
  src/main/java/com/travel/role/global/exception/accounting/AccountingInfoCannotBeDeletedException.java
  src/main/java/com/travel/role/global/exception/accounting/AccountingInfoCannotBeModifiedException.java
  src/main/java/com/travel/role/global/exception/accounting/AccountingInfoNotFoundException.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
Labels: 🛠️Fix

#162 Refactor #161파일및패키지명변경
  src/main/java/com/travel/role/domain/accounting/dto/response/ExpenseDetailResDTO.java
  src/main/java/com/travel/role/domain/accounting/entity/AccountingInfo.java
  src/main/java/com/travel/role/domain/board/service/BoardReadService.java
  src/main/java/com/travel/role/domain/book/controller/BookController.java
  src/main/java/com/travel/role/domain/book/dto/request/BookInfoRequestDTO.java
  src/main/java/com/travel/role/domain/book/dto/request/BookModifyRequestDTO.java
  src/main/java/com/travel/role/domain/book/dto/request/BookedRequestDTO.java
  src/main/java/com/travel/role/domain/book/dto/response/BookInfoResponseDTO.java
  src/main/java/com/travel/role/domain/book/entity/BookInfo.java
  src/main/java/com/travel/role/domain/book/repository/BookInfoRepository.java
  src/main/java/com/travel/role/domain/book/service/BookReadService.java
  src/main/java/com/travel/role/domain/book/service/BookService.java
  src/main/java/com/travel/role/domain/room/entity/RoomRole.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/domain/schedule/dto/response/ScheduleResponseDTO.java
  src/main/java/com/travel/role/domain/schedule/entity/Board.java
  src/main/java/com/travel/role/domain/schedule/entity/ScheduleInfo.java
  src/main/java/com/travel/role/domain/schedule/repository/BoardRepository.java
  src/main/java/com/travel/role/domain/schedule/service/BoardReadService.java
  src/main/java/com/travel/role/domain/schedule/service/ScheduleService.java
  src/test/java/com/travel/role/unit/room/service/BookServiceTest.java
Labels: ♼Refactor

#163 Feat #160여행일정수정api작성
  src/main/java/com/travel/role/domain/book/controller/BookController.java
  src/main/java/com/travel/role/domain/book/dto/request/BookModifyRequestDTO.java
  src/main/java/com/travel/role/domain/book/service/BookReadService.java
  src/main/java/com/travel/role/domain/book/service/BookService.java
  src/main/java/com/travel/role/domain/schedule/controller/ScheduleController.java
  src/main/java/com/travel/role/domain/schedule/dto/request/ScheduleModifyRequestDTO.java
  src/main/java/com/travel/role/domain/schedule/dto/request/ScheduleRequestDTO.java
  src/main/java/com/travel/role/domain/schedule/entity/Board.java
  src/main/java/com/travel/role/domain/schedule/entity/ScheduleInfo.java
  src/main/java/com/travel/role/domain/schedule/service/BoardReadService.java
  src/main/java/com/travel/role/domain/schedule/service/ScheduleReadService.java
  src/main/java/com/travel/role/domain/schedule/service/ScheduleService.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
  src/test/java/com/travel/role/unit/room/service/BookServiceTest.java
Labels: 👀Feature, ♼Refactor

#164 Feat #156 특정 방 내의 댓글을 모두 삭제하는 기능과 특정 방 내의 특정 유저의 댓글을 모두 삭제하는 기능 작성
  src/main/java/com/travel/role/domain/comment/entity/Comment.java
  src/main/java/com/travel/role/domain/comment/repository/CommentRepository.java
  src/main/java/com/travel/role/domain/comment/repository/querydsl/CommentQuerydsl.java
  src/main/java/com/travel/role/domain/comment/repository/querydsl/CommentQuerydslImpl.java
  src/main/java/com/travel/role/domain/comment/service/CommentService.java
Labels: 👀Feature

#166 fix: 컬럼 추가
  src/main/java/com/travel/role/domain/wantplace/dto/request/WantPlaceRequestDTO.java
  src/main/java/com/travel/role/domain/wantplace/dto/response/WantPlaceDTO.java
  src/main/java/com/travel/role/domain/wantplace/entity/WantPlace.java
  src/test/java/com/travel/role/unit/room/service/RoomServiceTest.java
Labels: 🛠️Fix

#168 Feat #167 특정 방 준비물 삭제, 특정 방 내의 특정 유저 준비물 삭제 기능 구현
  src/main/java/com/travel/role/domain/travelessential/repository/TravelEssentialRepository.java
  src/main/java/com/travel/role/domain/travelessential/service/TravelEssentialService.java
Labels: 👀Feature

#171 Feat #169 해당 유저의 역할 정보를 가져오는 API 작성
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/service/ParticipantRoleReadService.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
  src/main/java/com/travel/role/global/exception/room/RolesIsEmptyException.java
Labels: 👀Feature

#172 Hotfix Enum및, ConcurrentModificationException 해결
  src/main/java/com/travel/role/domain/room/entity/RoomRole.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
Labels: 🐞BugFix

#173 Hotfix enum convert
  src/main/java/com/travel/role/domain/room/entity/RoomRole.java
Labels: 🐞BugFix

#178 fix: 필드명 수정
  src/main/java/com/travel/role/domain/book/dto/response/BookInfoResponseDTO.java
Labels: 🛠️Fix

#175 Feat #169 스페이스 나가가기 기능
  src/main/java/com/travel/role/domain/accounting/repository/AccountingInfoRepository.java
  src/main/java/com/travel/role/domain/accounting/repository/querydsl/AccountingInfoQuerydsl.java
  src/main/java/com/travel/role/domain/accounting/repository/querydsl/AccountingInfoQuerydslImpl.java
  src/main/java/com/travel/role/domain/accounting/service/AccountingInfoReadService.java
  src/main/java/com/travel/role/domain/book/repository/BookInfoRepository.java
  src/main/java/com/travel/role/domain/comment/repository/CommentRepository.java
  src/main/java/com/travel/role/domain/room/controller/RoomController.java
  src/main/java/com/travel/role/domain/room/dto/request/ExitRoomRequestDTO.java
  src/main/java/com/travel/role/domain/room/entity/RoomRole.java
  src/main/java/com/travel/role/domain/room/repository/ParticipantRoleRepository.java
  src/main/java/com/travel/role/domain/room/repository/RoomParticipantRepository.java
  src/main/java/com/travel/role/domain/room/repository/RoomRepository.java
  src/main/java/com/travel/role/domain/room/repository/querydsl/ParticipantRoleQuerydsl.java
  src/main/java/com/travel/role/domain/room/repository/querydsl/ParticipantRoleQuerydslImpl.java
  src/main/java/com/travel/role/domain/room/repository/querydsl/RoomParticipantQuerydsl.java
  src/main/java/com/travel/role/domain/room/repository/querydsl/RoomParticipantQuerydslImpl.java
  src/main/java/com/travel/role/domain/room/repository/querydsl/RoomQuerydsl.java
  src/main/java/com/travel/role/domain/room/repository/querydsl/RoomQuerydslImpl.java
  src/main/java/com/travel/role/domain/room/service/ParticipantRoleReadService.java
  src/main/java/com/travel/role/domain/room/service/RoomParticipantReadService.java
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/domain/schedule/repository/BoardRepository.java
  src/main/java/com/travel/role/domain/schedule/repository/ScheduleInfoRepository.java
  src/main/java/com/travel/role/domain/schedule/service/ScheduleService.java
  src/main/java/com/travel/role/domain/travelessential/entity/TravelEssential.java
  src/main/java/com/travel/role/domain/wantplace/repository/WantPlaceRepository.java
  src/test/java/com/travel/role/integration/room/RoomTest.java
  src/test/resources/db/test.sql
Labels: 👀Feature

#176 Hotfix RoomUpdate 로직 오류 수정
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/main/java/com/travel/role/global/exception/GlobalExceptionHandler.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
  src/main/java/com/travel/role/global/exception/room/RoomNotUpdateAdminException.java
  src/test/java/com/travel/role/integration/room/RoomTest.java
  src/test/java/com/travel/role/unit/room/service/RoomServiceTest.java
Labels: 🛠️Fix

#180 fix: dto를 넣어야하는것을 Entity를 넣는 오탈자 수정 및 테스트 코드 추가
  src/main/java/com/travel/role/domain/room/service/RoomService.java
  src/test/java/com/travel/role/integration/room/RoomTest.java
Labels: 🐞BugFix

#179 Feat #170 Aws SES 서비스로 Email 전송 변경
  build.gradle
  src/main/java/com/travel/role/domain/user/controller/UserController.java
  src/main/java/com/travel/role/global/auth/service/mail/MailService.java
  src/main/java/com/travel/role/global/config/aws/AWSSESConfig.java
  src/main/resources/application-cloud.yml
Labels: 👀Feature

#184 Feat #183 특정 방의 총 지출 내역을 조회하는 api 작성
  src/main/java/com/travel/role/domain/accounting/controller/AccountingInfoController.java
  src/main/java/com/travel/role/domain/accounting/dto/response/ExpenseDetailsResDTO.java
  src/main/java/com/travel/role/domain/accounting/dto/response/TotalExpenseDetailResDTO.java
  src/main/java/com/travel/role/domain/accounting/repository/querydsl/AccountingInfoQuerydsl.java
  src/main/java/com/travel/role/domain/accounting/repository/querydsl/AccountingInfoQuerydslImpl.java
  src/main/java/com/travel/role/domain/accounting/service/AccountingInfoReadService.java
  src/main/java/com/travel/role/global/auth/service/handler/OAuth2FailureHandler.java
Labels: 👀Feature

#181 Feat #152 도메인 설정 변경 및 쿠기 설정 변경
  src/main/java/com/travel/role/global/auth/service/RefreshTokenCookieProvider.java
  src/main/resources/application-oauth.yml
Labels: 💻Deploy

#186 hotfix: 지출 내역이 입력되지 않았을 때, null 이 아닌 0 을 반환하도록 수정
  src/main/java/com/travel/role/domain/accounting/dto/response/TotalExpenseDetailResDTO.java
  src/main/java/com/travel/role/domain/accounting/repository/querydsl/AccountingInfoQuerydsl.java
  src/main/java/com/travel/role/domain/accounting/repository/querydsl/AccountingInfoQuerydslImpl.java
  src/main/java/com/travel/role/domain/accounting/service/AccountingInfoReadService.java
Labels: 🐞BugFix, 🛠️Fix

#185 Feat #174 준비물 Controller 단위 테스트 작성
  src/main/java/com/travel/role/domain/travelessential/controller/TravelEssentialController.java
  src/main/java/com/travel/role/domain/travelessential/dto/request/TravelEssentialCheckReqDTO.java
  src/main/java/com/travel/role/domain/travelessential/dto/request/TravelEssentialReqDTO.java
  src/main/java/com/travel/role/global/exception/GlobalExceptionHandler.java
  src/main/java/com/travel/role/global/exception/dto/ExceptionMessage.java
  src/test/java/com/travel/role/unit/ControllerTestSupport.java
  src/test/java/com/travel/role/unit/travelessential/controller/TravelEssentialControllerTest.java
Labels: ✅Test, 🛠️Fix, ♼Refactor

#188 hotfix: 지출 내역 조회, 수정 DTO 비고 필드명 통일
  src/main/java/com/travel/role/domain/accounting/dto/request/ExpenseDetailCreateReqDTO.java
  src/main/java/com/travel/role/domain/accounting/dto/request/ExpenseDetailModifyReqDTO.java
  src/main/java/com/travel/role/domain/accounting/dto/response/ExpenseDetailCreateResDTO.java
  src/main/java/com/travel/role/domain/accounting/dto/response/ExpenseDetailModifyResDTO.java
  src/main/java/com/travel/role/domain/accounting/service/AccountingInfoService.java
Labels: 🛠️Fix, ♼Refactor

#189 fix: 유효성 검사 해지
  src/main/java/com/travel/role/domain/wantplace/dto/request/WantPlaceRequestDTO.java
Labels: 🛠️Fix, ♼Refactor

#191 fix: paymentTime수정
  src/main/java/com/travel/role/domain/book/service/BookService.java
Labels: 🛠️Fix, ♼Refactor
